support nullsafety
lucaslcode/outline_material_icons pull request #6
Opened 2021-02-20 19:16 UTC by Ahmadre

I use this package for my flutter_iconpicker package and my users needs nullsafety.

So I did:

`dart migrate --apply-changes`

to be able to support nullsafety.

There're no relevant changes, just the sdk version changed.

2021-03-07 14:38 UTC, nilsreichardt requested changes

2021-03-07 14:38 UTC, nilsreichardt commented on pubspec.yaml
> +version: 0.2.0-nullsafety
Null safety is now stable so we can remove the prerelease

```suggestion
version: 0.2.0
```

2021-03-07 14:38 UTC, nilsreichardt commented on CHANGELOG.md
> +## [0.2.0-nullsafety] - 20/02/2021
Null safety is now stable so we can remove the prerelease

```suggestion
## [0.2.0] - 20/02/2021
```

2021-03-10 10:37 UTC, Ahmadre commented on pubspec.yaml
> +version: 0.2.0-nullsafety
And I was questening myself why others do this "-nullsafety" but now it's clear for me xD thx!

2021-05-10 22:35 UTC, emlynmac commented
Any chance to get this merged soon? It's one of the dependencies holding me up from migrating to null-safety.

2021-05-11 10:46 UTC, nilsreichardt commented
@emlynmac As a workaround you should be able to use this in your `pubspec.yaml`:

```yaml
outline_material_icons:
  git:
    url: https://github.com/Ahmadre/outline_material_icons
```

2021-05-11 20:01 UTC, Ahmadre commented
> Any chance to get this merged soon? It's one of the dependencies holding me up from migrating to null-safety.

The outlined icons are now integrated in new flutter versions. Including rounded and so on.

But regarding the null safety problem: just add:

// @dart=2.9

on top of your main.dart file

2023-12-11 05:36 UTC, closed without merging